services:
  wikijs:
    image: lscr.io/linuxserver/wikijs:latest
    container_name: wikijs
    networks:
    - frontend
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.wikijs.rule=Host(`wikibut.vindiesel.vip`)"
        - "traefik.http.routers.wikijs.entrypoints=websecure"
        - "traefik.http.routers.wikijs.tls=true"
        - "traefik.http.routers.wikijs.tls.certresolver=letencrypt"
        - "traefik.http.services.wikijs.loadbalancer.server.port=3000"
        - "traefik.http.routers.wikijs.entrypoints=web"
        - "traefik.http.routers.wikijs.middlewares=redirect-to-https"
        - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    volumes:
      - /home/portainer/wikijs/config:/config
      - /home/portainer/wikijs/data:/data
    ports:
      - 3000:3000
    restart: unless-stopped

networks:
  frontend:
    name: frontend
    external: true