services:
  traefik:
    image: traefik
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    environment:
      - TZ=Europe/Paris
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    networks:
      - frontend
    ports:
      - 80:80 # Port HTTP
      - 443:443 # Port HTTPS
      - 8080:8080 # Accès dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${TRAEFIK_FILES}:/traefik.yml:ro
      - ${TRAEFIK_FILES}:/certs

volumes:
  traefik:
    name: traefik

networks:
  frontend:
    name: frontend
