api:
  dashboard: true
  insecure: true
  debug: false
entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
serversTransport:
  insecureSkipVerify: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
certificatesResolvers:
  letencrypt:
    acme:
      email: [EMAIL]
      storage: /certs/acme.json
      # caServer: https://acme-v02.api.letsencrypt.org/directory # prod (default)
      caServer: https://acme-staging-v02.api.letsencrypt.org/directory # staging
      # Use **one** of the following challenge types:
      # --- DNS Challenge (example: Cloudflare) ---
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 10

      # --- HTTP Challenge ---
      httpChallenge:
        entryPoint: web